# Generated by Django 3.2.7 on 2021-09-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_1_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
