# Generated by Django 3.2.6 on 2021-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0011_entity01_att_11_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity01',
            name='att_10_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_11_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_2_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_3_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_4_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_5_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_6_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_7_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_8_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_9_text',
        ),
        migrations.AlterField(
            model_name='entity01',
            name='att_1_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
