# Generated by Django 3.2.6 on 2021-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0012_entity01_att_12_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity01',
            name='att_13_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
