# Generated by Django 3.2.6 on 2021-08-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0018_entity01_att_7_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity01',
            name='att_2_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_3_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_4_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_5_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_6_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_7_text',
        ),
    ]
