# Generated by Django 3.2.6 on 2021-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0019_auto_20210820_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity01',
            name='att_2_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
