# Generated by Django 3.2.7 on 2021-09-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0130_entity01_att_10_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity01',
            name='att_10_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_2_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_3_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_4_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_5_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_6_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_7_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_8_text',
        ),
        migrations.RemoveField(
            model_name='entity01',
            name='att_9_text',
        ),
    ]
