# Generated by Django 3.2.7 on 2021-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys01_web', '0151_auto_20210909_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity01',
            name='att_2_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
