from django.db import models

class Entity01(models.Model):
    att_1_text = models.CharField(max_length=200, null=True, blank=True)
    att_2_text = models.CharField(max_length=200, null=True, blank=True)
    att_3_text = models.CharField(max_length=200, null=True, blank=True)
    att_4_text = models.CharField(max_length=200, null=True, blank=True)
    att_5_text = models.CharField(max_length=200, null=True, blank=True)
    att_6_text = models.CharField(max_length=200, null=True, blank=True)
    att_7_text = models.CharField(max_length=200, null=True, blank=True)
    att_8_text = models.CharField(max_length=200, null=True, blank=True)
    att_9_text = models.CharField(max_length=200, null=True, blank=True)
    att_10_text = models.CharField(max_length=200, null=True, blank=True)
    att_11_text = models.CharField(max_length=200, null=True, blank=True)
    att_12_text = models.CharField(max_length=200, null=True, blank=True)
    att_13_text = models.CharField(max_length=200, null=True, blank=True)
    att_14_text = models.CharField(max_length=200, null=True, blank=True)
    att_15_text = models.CharField(max_length=200, null=True, blank=True)
    att_16_text = models.CharField(max_length=200, null=True, blank=True)
    att_17_text = models.CharField(max_length=200, null=True, blank=True)
    att_18_text = models.CharField(max_length=200, null=True, blank=True)
    att_19_text = models.CharField(max_length=200, null=True, blank=True)
    att_20_text = models.CharField(max_length=200, null=True, blank=True)
    att_21_text = models.CharField(max_length=200, null=True, blank=True)
    att_22_text = models.CharField(max_length=200, null=True, blank=True)
    att_23_text = models.CharField(max_length=200, null=True, blank=True)